apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: voiting
  name: voiting-controller
spec:
  replicas: 1
  selector:
    name: voiting
  template:
    metadata:
      labels:
        name: voiting
    spec:
      containers:
        - image: akitoshka/app:latest
          name: voiting
          ports:
            - containerPort: 8000
              name: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: ClusterIP
  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 8000
  selector:
    name: voiting
